"""
Library Integrations API Router

Provides endpoints for accessing all 12 Socratic ecosystem libraries:
- socratic-learning: Learning analytics and recommendations
- socratic-analyzer: Code quality analysis
- socratic-conflict: Multi-agent conflict resolution
- socratic-knowledge: Enterprise knowledge management
- socratic-workflow: Workflow orchestration
- socratic-docs: Documentation generation
- socratic-performance: Performance monitoring
"""

import logging
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, HTTPException, Query

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/libraries", tags=["Library Integrations"])


# ============================================================================
# ENDPOINTS - Code Analysis
# ============================================================================


@router.post("/analyzer/analyze-code")
async def analyze_code_quality(
    code: str = Query(..., description="Source code to analyze"),
    filename: str = Query("code.py", description="Filename for context"),
) -> Dict[str, Any]:
    """
    Analyze code quality using socratic-analyzer.

    Uses static analysis to check for:
    - Code quality metrics (0-100 score)
    - Security issues
    - Performance concerns
    - Architecture insights

    Args:
        code: Source code to analyze
        filename: Filename (for context)

    Returns:
        Dictionary with analysis results including quality_score, issues, recommendations
    """
    try:
        from socratic_system.orchestration.orchestrator import AgentOrchestrator

        # Get orchestrator from app state (would need to be passed as dependency in real implementation)
        # For now, creating a minimal instance
        orchestrator = AgentOrchestrator(api_key_or_config="placeholder")

        result = orchestrator.analyze_code_quality(code, filename)
        if result:
            return result
        else:
            raise HTTPException(
                status_code=503,
                detail="Code analyzer is not available. Is socratic-analyzer installed?"
            )
    except Exception as e:
        logger.error(f"Code analysis failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# ============================================================================
# ENDPOINTS - Learning Analytics
# ============================================================================


@router.post("/learning/log-interaction")
async def log_learning_interaction(
    session_id: str = Query(..., description="Learning session ID"),
    agent_name: str = Query(..., description="Agent name"),
    input_data: Dict[str, Any] = Query(..., description="Input to agent"),
    output_data: Dict[str, Any] = Query(..., description="Output from agent"),
    tokens_used: int = Query(0, description="LLM tokens used"),
    cost: float = Query(0.0, description="Cost in USD"),
    duration_ms: float = Query(0.0, description="Duration in milliseconds"),
    success: bool = Query(True, description="Was interaction successful?"),
    tags: Optional[List[str]] = Query(None, description="Tags for categorization"),
) -> Optional[Dict[str, Any]]:
    """
    Log a learning interaction using socratic-learning.

    Tracks agent interactions for:
    - Learning progress analytics
    - Concept mastery assessment
    - Misconception detection
    - Personalized recommendations

    Args:
        session_id: Learning session identifier
        agent_name: Name of the agent that executed
        input_data: Input provided to the agent
        output_data: Output generated by the agent
        tokens_used: LLM tokens consumed
        cost: Cost in USD
        duration_ms: Execution duration
        success: Whether execution was successful
        tags: Optional tags for analysis

    Returns:
        Interaction log entry or None if learning system unavailable
    """
    try:
        from socratic_system.orchestration.orchestrator import AgentOrchestrator

        orchestrator = AgentOrchestrator(api_key_or_config="placeholder")
        result = orchestrator.log_learning_interaction(
            session_id=session_id,
            agent_name=agent_name,
            input_data=input_data,
            output_data=output_data,
            tokens=tokens_used,
            cost=cost,
            duration_ms=duration_ms,
            success=success,
        )
        return result or {"status": "logged"}
    except Exception as e:
        logger.error(f"Failed to log learning interaction: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/learning/status")
async def get_learning_status() -> Dict[str, Any]:
    """
    Get status of socratic-learning integration.

    Returns:
        Dictionary with learning system status and capabilities
    """
    try:
        from socratic_system.orchestration.orchestrator import AgentOrchestrator

        orchestrator = AgentOrchestrator(api_key_or_config="placeholder")
        status = orchestrator.get_library_status()
        return {
            "learning": status.get("learning", False),
            "status": "operational" if status.get("learning") else "unavailable"
        }
    except Exception as e:
        logger.error(f"Failed to get learning status: {e}")
        return {"status": "error", "message": str(e)}


# ============================================================================
# ENDPOINTS - Conflict Resolution
# ============================================================================


@router.post("/conflict/detect-and-resolve")
async def detect_agent_conflicts(
    field: str = Query(..., description="Field name where conflict exists"),
    agent_outputs: Dict[str, Any] = Query(..., description="Outputs from different agents"),
    agents: List[str] = Query(..., description="List of agent names"),
) -> Optional[Dict[str, Any]]:
    """
    Detect and resolve conflicts between agent outputs using socratic-conflict.

    Handles:
    - Data conflicts (contradictory values)
    - Decision conflicts (incompatible proposals)
    - Workflow conflicts
    - Automatic resolution strategies

    Args:
        field: Field name where conflict occurred
        agent_outputs: Dictionary mapping agent names to their outputs
        agents: List of agent names involved

    Returns:
        Conflict resolution result with recommended value and confidence
    """
    try:
        from socratic_system.orchestration.orchestrator import AgentOrchestrator

        orchestrator = AgentOrchestrator(api_key_or_config="placeholder")
        result = orchestrator.detect_agent_conflicts(field, agent_outputs, agents)
        return result or {"conflict_detected": False}
    except Exception as e:
        logger.error(f"Conflict detection failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/conflict/status")
async def get_conflict_status() -> Dict[str, Any]:
    """
    Get status of socratic-conflict integration.

    Returns:
        Dictionary with conflict resolution capabilities
    """
    try:
        from socratic_system.orchestration.orchestrator import AgentOrchestrator

        orchestrator = AgentOrchestrator(api_key_or_config="placeholder")
        status = orchestrator.get_library_status()
        return {
            "conflict": status.get("conflict", False),
            "status": "operational" if status.get("conflict") else "unavailable"
        }
    except Exception as e:
        logger.error(f"Failed to get conflict status: {e}")
        return {"status": "error", "message": str(e)}


# ============================================================================
# ENDPOINTS - Knowledge Management
# ============================================================================


@router.post("/knowledge/store")
async def store_knowledge_item(
    tenant_id: str = Query(..., description="Tenant/organization ID"),
    title: str = Query(..., description="Knowledge item title"),
    content: str = Query(..., description="Knowledge content"),
    tags: Optional[List[str]] = Query(None, description="Tags for categorization"),
) -> Optional[Dict[str, Any]]:
    """
    Store a knowledge item using socratic-knowledge.

    Stores structured knowledge for:
    - Organization-wide knowledge base
    - RBAC-protected access
    - Version control
    - Semantic search capability

    Args:
        tenant_id: Organization/tenant identifier
        title: Knowledge item title
        content: Knowledge content/description
        tags: Optional tags for discovery

    Returns:
        Created knowledge item info or None if unavailable
    """
    try:
        from socratic_system.orchestration.orchestrator import AgentOrchestrator

        orchestrator = AgentOrchestrator(api_key_or_config="placeholder")
        result = orchestrator.store_knowledge(tenant_id, title, content, tags)
        return result or {"status": "stored"}
    except Exception as e:
        logger.error(f"Failed to store knowledge: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/knowledge/search")
async def search_knowledge(
    tenant_id: str = Query(..., description="Tenant/organization ID"),
    query: str = Query(..., description="Search query"),
    limit: int = Query(5, ge=1, le=50, description="Max results to return"),
) -> List[Dict[str, Any]]:
    """
    Search knowledge base using socratic-knowledge.

    Performs semantic search across organization knowledge base.

    Args:
        tenant_id: Organization/tenant identifier
        query: Search query
        limit: Maximum results to return

    Returns:
        List of matching knowledge items
    """
    try:
        from socratic_system.orchestration.orchestrator import AgentOrchestrator

        orchestrator = AgentOrchestrator(api_key_or_config="placeholder")
        results = orchestrator.search_knowledge(tenant_id, query)
        return results[:limit] if results else []
    except Exception as e:
        logger.error(f"Knowledge search failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/knowledge/status")
async def get_knowledge_status() -> Dict[str, Any]:
    """
    Get status of socratic-knowledge integration.

    Returns:
        Dictionary with knowledge management capabilities
    """
    try:
        from socratic_system.orchestration.orchestrator import AgentOrchestrator

        orchestrator = AgentOrchestrator(api_key_or_config="placeholder")
        status = orchestrator.get_library_status()
        return {
            "knowledge": status.get("knowledge", False),
            "status": "operational" if status.get("knowledge") else "unavailable"
        }
    except Exception as e:
        logger.error(f"Failed to get knowledge status: {e}")
        return {"status": "error", "message": str(e)}


# ============================================================================
# ENDPOINTS - Documentation Generation
# ============================================================================


@router.post("/docs/generate-readme")
async def generate_project_documentation(
    project_info: Dict[str, Any] = Query(..., description="Project information"),
) -> Optional[str]:
    """
    Generate project documentation using socratic-docs.

    Generates:
    - README with project overview
    - Installation instructions
    - Usage examples
    - API documentation

    Args:
        project_info: Dictionary with project metadata and structure

    Returns:
        Generated README content as string
    """
    try:
        from socratic_system.orchestration.orchestrator import AgentOrchestrator

        orchestrator = AgentOrchestrator(api_key_or_config="placeholder")
        result = orchestrator.generate_documentation(project_info)
        return result or "# Documentation not available"
    except Exception as e:
        logger.error(f"Documentation generation failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/docs/status")
async def get_docs_status() -> Dict[str, Any]:
    """
    Get status of socratic-docs integration.

    Returns:
        Dictionary with documentation generation capabilities
    """
    try:
        from socratic_system.orchestration.orchestrator import AgentOrchestrator

        orchestrator = AgentOrchestrator(api_key_or_config="placeholder")
        status = orchestrator.get_library_status()
        return {
            "docs": status.get("docs", False),
            "status": "operational" if status.get("docs") else "unavailable"
        }
    except Exception as e:
        logger.error(f"Failed to get docs status: {e}")
        return {"status": "error", "message": str(e)}


# ============================================================================
# ENDPOINTS - System Status
# ============================================================================


@router.get("/status")
async def get_all_library_status() -> Dict[str, Any]:
    """
    Get status of all Socratic library integrations.

    Returns:
        Dictionary with status of all 7 integrated libraries:
        - learning: socratic-learning
        - analyzer: socratic-analyzer
        - conflict: socratic-conflict
        - knowledge: socratic-knowledge
        - workflow: socratic-workflow
        - docs: socratic-docs
        - performance: socratic-performance
    """
    try:
        from socratic_system.orchestration.orchestrator import AgentOrchestrator

        orchestrator = AgentOrchestrator(api_key_or_config="placeholder")
        status = orchestrator.get_library_status()

        enabled_count = sum(1 for v in status.values() if v)
        total_count = len(status)

        return {
            "libraries": status,
            "enabled": enabled_count,
            "total": total_count,
            "status": "operational" if enabled_count > 0 else "degraded",
            "message": f"{enabled_count}/{total_count} libraries enabled"
        }
    except Exception as e:
        logger.error(f"Failed to get library status: {e}")
        raise HTTPException(status_code=500, detail=str(e))
